### PR TITLE
mmap-alloc: Improve tests for permissions, fix realloc bugs

### LINKED ISSUE #72: mmap-alloc: Implement mark_unused for Windows
On Linux and Mac, we have a `mark_unused` function that is used when a mapping call returns 0. In this case, we request a different mapping, but leave the 0 page mapped so that future calls will never return that page again. In order to make bugs easier to find and to avoid wasting resources, we call `mark_unused` on the page, which informs the kernel that we don't need a physical page to back it, and sets the page's permissions to `PROT_NONE` so that any future accesses will result in a segfault.

Equivalents to this behavior probably exist on Windows, so we should implement `mark_unused` for Windows as well.

### LINKED ISSUE #80: mmap-alloc: Document that alloc_helper requires a page-multiple size
`alloc_helper` includes the following code:

```rust
let unmap_size = size - allocator.pagesize;
if unmap_size > 0 {
    unmap(allocator.pagesize as *mut u8, unmap_size);
}
```

This code is only correct if `size` is at least as large as `allocator.pagesize`. Currently, we always call `alloc_helper` with a size that is rounded up to the next multiple of the page size, so this is fine. However, we should a) document this requirement and, b) add a `debug_assert!` to ensure that it holds.

### LINKED ISSUE #83: mmap-alloc: Change permissions before reallocing
On non-Linux platforms, the default `realloc` implementation is used. This breaks when either of the read or write permissions is not configured because the default implementation allocates a new object and then manually copies the bytes from the old to the new. Thus, we need to override `realloc` in order to temporarily change the memory permissions, perform the copy, and then change the permissions back.

### PR DESCRIPTION
**Pull request by joshlf**
- Add the ability to parse `/proc/<pid>/maps` on Linux, and incorporate this into existing tests in order to verify permissions
- Remove checks for allocation at the 0 page, as it turns out that these are unnecessary on all platforms that we support (Linux, Mac, Windows)
- Change the way boolean configuration functions work for `MapAllocBuilder` (instead of `xxx()` and `no_xxx()`, we now supply a single `xxx(xxx: bool)` method that accepts a boolean indicating whether the configuration should be on or off)
- Move tests module into separate file

Closes #83.
Closes #72 and #80 by making them unnecessary since this commit removes the use cases for `mark_unused` and `alloc_helper`.

For posterity: A previous version of the code to verify memory permissions attempted to access a region in order to generate a SIGSEGV signal, and catch that signal. I couldn't get that code working, so I switched to parsing `/proc/<pid>/maps` instead. If somebody wants to take a look and maybe try to get it working, the draft I had before I switched is [here](https://gist.github.com/joshlf/d4af584e4722aebe7f3dfc6050dbbf3d).

### CODE REVIEW

**Comment by joshlf** [comment]
@Dr-Emann Just wanted to give you a heads up about this - I came across a line about Linux guaranteeing non-null addresses from `mmap` while reading the manpage, and when I dug further, I realized it's guaranteed on POSIX in general (meaning Mac as well). This unfortunately means that a lot of the work you did in the previous PR is taken out in this PR as it's unnecessary (the same goes for some code that I wrote previously to handle the same case for allocation). I'm sorry to have you go through all of that just to have the code removed a couple of days later.

I will say that I'm not 100% convinced about the manpage being correct - both @ezrosent and I have recollections (mine in the form of a comment in `test.rs`, actually) that Linux has, on occasion, returned null from `mmap`. However, when I tested this on play.rust-lang.org, I couldn't reproduce it. I'm going to investigate more fully before I merge this PR.

**Comment by Dr-Emann** [comment]
Can I cast my vote against formatting multiline functions definitions this way? Besides my personal bias (I think it's incredibly ugly), it's [no longer the recommended format for rust code](https://github.com/rust-lang-nursery/fmt-rfcs/issues/39#issuecomment-278544439), and using the newer [rustfmt-nightly](https://github.com/rust-lang-nursery/rustfmt) formats it much [better](https://play.rust-lang.org/?gist=88286b6da1d54833eb87f725da2858b3&version=stable) (see also, the format button on the playground)

**Comment by Dr-Emann** [comment]
As for mapping returning null: don't worry about it. It was fun figuring how to deal with it, even if it would never happen. 

fyi, I did mention that posix seemed to disallow returning null from mmap without MAP_FIXED in the description of my pull request.  😜

**Comment by joshlf** [comment]
> Can I cast my vote against formatting multiline functions definitions this way? Besides my personal bias (I think it's incredibly ugly), it's no longer the recommended format for rust code, and using the newer rustfmt-nightly formats it much better (see also, the format button on the playground)

Oh, absolutely! I've been using stable rustfmt, but I'm happy to switch to rustfmt-nightly; I just didn't remember it was a thing so I never installed it.

> fyi, I did mention that posix seemed to disallow returning null from mmap without MAP_FIXED in the description of my pull request. 😜

Shit you're right - I see that now (and I think I know why I didn't catch it before). That's totally my bad. Your point in that original comment about explicitly mapping a null page is a good one! I think I'll add that point to my comment in this PR so if it becomes an issue in the future, we'll have a comment with an idea of how to fix it.

**Comment by joshlf** [comment]
OK, looks like [we're good on Mac](https://stackoverflow.com/a/46356612/836390) with respect to mapping the null page.

File: mmap-alloc/src/lib.rs [hunk 1]
```diff
@@ -411,90 +277,190 @@ impl MapAlloc {
...
+        // otherwise, fall back on alloc + copy + dealloc.
+        let result = Alloc::alloc(self, new_layout);
+        if let Ok(new_ptr) = result {
+            use core::cmp;
+
+            // Temporarily mark the old allocation readable and the new allocation writable in case
+            // we're configured to allocate un-readable or un-writable memory - we'll need to be
+            // able to read/write in order to copy the data.
+            protect(ptr, old_size, perms::PROT_READ);
+            protect(new_ptr, new_size, perms::PROT_WRITE);
```
Comment (Dr-Emann) [inline mmap-alloc/src/lib.rs]: Even though reallocation should be infrequent, I'm not sure how I feel about 3 guaranteed syscalls, when in most cases none would be needed (I'd expect most allocators to expect read+write)

File: mmap-alloc/src/tests.rs [hunk 2]
```diff
@@ -0,0 +1,584 @@
...
+    map.insert(String::from("r-xp"), PROT_READ_EXEC);
+    map.insert(String::from("-wxp"), PROT_WRITE_EXEC);
+    map.insert(String::from("rwxp"), PROT_READ_WRITE_EXEC);
+
+    let mut blocks = Vec::new();
+
+    let output = Command::new("cat")
+        .arg(format!("/proc/{}/maps", unsafe { libc::getpid() }))
+        .output()
+        .unwrap();
```
Comment (Dr-Emann) [inline mmap-alloc/src/tests.rs]: Is there a reason to use cat vs opening the file ourselves with std::fs::File?

Comment (joshlf) [reply mmap-alloc/src/tests.rs]: This was adapted from an earlier version of the function whose job was to get the permissions for a _particular_ address block, and thus was a more complicated command involving a full sequence of commands chained together with pipes. I honestly didn't even notice what this ended up getting whittled down to - I'll change it.

File: mmap-alloc/src/lib.rs (hunk 1 above)
Comment (joshlf) [reply mmap-alloc/src/lib.rs]: Good call. I'll check the perms first.

**Comment by joshlf** [comment]
I've been [so far unable](https://stackoverflow.com/questions/46411766/can-mremap-place-mappings-at-0) to find documentation conclusively stating that `mremap` won't return null. However, I did find that in the Linux 4.13.3 source, `mremap`, when called without `REMAP_FIXED`, [works by calling `get_unmapped_area`](http://elixir.free-electrons.com/linux/v4.13.3/source/mm/mremap.c#L607). I can't see conclusively from the source that `get_unmapped_area` never returns null. However, what I _can_ see is that `get_unmapped_area` is also used to [implement `mmap`](http://elixir.free-electrons.com/linux/v4.13.3/source/mm/mmap.c#L1363), and we're already confident that `mmap` (without the `MAP_FIXED` flag) does not return null. That, combined with the fact that if it turns out we're wrong, we'll catch it in an unconditional `assert!` in the Linux implementation of the private `map` function, makes me confident enough to merge this.

**Comment by joshlf** [comment]
@Dr-Emann, I'll let you weigh in first, but otherwise I'm ready to merge this.

File: mmap-alloc/src/lib.rs [hunk 3]
```diff
@@ -411,90 +283,199 @@ impl MapAlloc {
...
+            if new_size >= old_size {
+                if let Ok(()) = self.grow_in_place(ptr, layout.clone(), new_layout.clone()) {
+                    return Ok(ptr);
+                }
+            } else if new_size < old_size {
+                if let Ok(()) = self.shrink_in_place(ptr, layout.clone(), new_layout.clone()) {
+                    return Ok(ptr);
+                }
+            }
+        }
```
Comment (Dr-Emann) [inline mmap-alloc/src/lib.rs]: Since we're not overriding shrink_in_place for macos either, I don't think this makes sense to have. The cases which would be handled by the default implementation (and are handled for macos and windows) should already be handled by the `old_size == new_size` check above, which checks if the old layout and the new layout both round  up to the same size.

File: mmap-alloc/src/lib.rs [hunk 4]
```diff
@@ -255,6 +231,9 @@ impl Default for MapAllocBuilder {
 pub struct MapAlloc {
     pagesize: usize,
     huge_pagesize: Option<usize>,
+    #[cfg_attr(target_os = "linux", allow(unused))] read: bool,
+    #[cfg_attr(target_os = "linux", allow(unused))] write: bool,
+    #[cfg_attr(target_os = "linux", allow(unused))] exec: bool,
```
Comment (Dr-Emann) [inline mmap-alloc/src/lib.rs]: It seems unfortunate to have this duplication (the same info should be stored in the `perms` field. Could we either:

1. Use helper fns like `perms::can_read(Perm)`
2. Make Perm a real type (maybe using [bitflags](https://crates.io/crates/bitflags), with a method `to_os_perm()` which returns the right type depending on the OS? The custom type could support tests like `perm.contains(perms::READ)`.

File: mmap-alloc/src/lib.rs [hunk 5]
```diff
@@ -411,90 +283,199 @@ impl MapAlloc {
...
+    unsafe fn grow_in_place(
+        &mut self,
+        ptr: *mut u8,
+        layout: Layout,
+        new_layout: Layout,
+    ) -> Result<(), CannotReallocInPlace> {
+        debug_assert!(
+            layout.size() > 0 && new_layout.size() > 0,
+            "grow_in_place: size of layout and new_layout must be non-zero"
+        );
```
Comment (Dr-Emann) [inline mmap-alloc/src/lib.rs]: I think I'd split this into two asserts, but I don't have a strong opinion either way.

File: mmap-alloc/src/lib.rs [hunk 6]
```diff
@@ -511,7 +492,17 @@ unsafe impl<'a> Alloc for &'a MapAlloc {
...
+    unsafe fn shrink_in_place(
+        &mut self,
+        ptr: *mut u8,
+        layout: Layout,
+        new_layout: Layout,
+    ) -> Result<(), CannotReallocInPlace> {
+        debug_assert!(
+            layout.size() > 0 && new_layout.size() > 0,
+            "shrink_in_place: size of layout and new_layout must be non-zero"
+        );
```
Comment (Dr-Emann) [inline mmap-alloc/src/lib.rs]: Likewise for splitting the assert.

File: mmap-alloc/src/lib.rs [hunk 7]
```diff
@@ -411,90 +283,199 @@ impl MapAlloc {
...
+            // order to be able to copy the data.
+            let fix_permissions = !self.read || !self.write;
+            if fix_permissions {
+                protect(ptr, old_size, perms::get_perm(true, self.write, self.exec));
+                protect(
+                    new_ptr,
+                    new_size,
+                    perms::get_perm(self.read, true, self.exec),
+                );
+            }
```
Comment (Dr-Emann) [inline mmap-alloc/src/lib.rs]: I'd prefer to split this, so if reads are allowed, but not writes, there's no reason to fix permissions on the old allocations, only the new one, to allow writing, then reset them after. Likewise, for the opposite, if writes are allowed, but not reads, we only have to fix permissions on the old allocation, and never have to reset them back.

File: mmap-alloc/src/lib.rs (hunk 3 above)
Comment (Dr-Emann) [reply mmap-alloc/src/lib.rs]: Sorry, I hoped there would be more context in the preview. The block starts [here](https://github.com/ezrosent/allocators-rs/pull/87/files/3e5636db556f92e292af5ece2a13e21ab4809f89#diff-7be4d90297df3fdf7c0f62394837b6d5R423)

File: mmap-alloc/src/lib.rs (hunk 7 above)
Comment (Dr-Emann) [reply mmap-alloc/src/lib.rs]: Again, missing important context in the short preview. Starts [here](https://github.com/ezrosent/allocators-rs/pull/87/files/3e5636db556f92e292af5ece2a13e21ab4809f89#diff-7be4d90297df3fdf7c0f62394837b6d5R444)

File: mmap-alloc/src/lib.rs (hunk 4 above)
Comment (joshlf) [reply mmap-alloc/src/lib.rs]: I agree that this is a tad ugly, but given that we almost exclusively use perms as opaque, and only use the boolean functionality in one place (realloc), I think it's better to keep it simple.

File: mmap-alloc/src/lib.rs (hunk 3 above)
Comment (joshlf) [reply mmap-alloc/src/lib.rs]: I fixed this by implementing `shrink_in_place` on Mac and simplifying the logic here. How does that look?

File: mmap-alloc/src/lib.rs (hunk 7 above)
Comment (joshlf) [reply mmap-alloc/src/lib.rs]: Fixed.

File: mmap-alloc/src/lib.rs (hunk 5 above)
Comment (joshlf) [reply mmap-alloc/src/lib.rs]: Fixed.

File: mmap-alloc/src/lib.rs (hunk 6 above)
Comment (joshlf) [reply mmap-alloc/src/lib.rs]: Fixed.

**Comment by Dr-Emann** [comment]
I still think the read/write/exec bools are ugly, but other than that, it all looks good, I'd say this is ready to merge in my eyes.
